# Generated by Django 5.2.1 on 2025-05-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('cheque_type', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.bill')),
            ],
        ),
    ]
