# Generated by Django 5.2.1 on 2025-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_photo',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_Number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
