# Generated by Django 5.2.1 on 2025-05-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_remove_bill_remaining_amount_bill_assigned_to_and_more'),
        ('payments', '0004_remove_payment_transaction_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to='bills.bill'),
        ),
    ]
