# Generated by Django 5.2.1 on 2025-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upi_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Daily Payment Summary',
                'verbose_name_plural': 'Daily Payment Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
