# Generated by Django 5.2.1 on 2025-05-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=255)),
                ('invoice_number', models.PositiveBigIntegerField()),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('brand', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
