# Generated by Django 5.2.1 on 2025-05-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_populate_outlet_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.outlet'),
        ),
    ]
