# Generated by Django 5.2.1 on 2025-05-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(max_length=255),
        ),
    ]
