# Generated by Django 5.2.1 on 2025-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='overdue_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
