# Generated by Django 5.2.1 on 2025-05-30 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_remove_bill_amount_remove_bill_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'dra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared')], default='open', max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
