# Generated by Django 5.2.1 on 2025-05-30 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_remove_bill_remaining_amount_bill_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='actual_amount minus all payments', max_digits=10),
        ),
    ]
